### ISSUE TITLE
fixincludes.pl not found

### ISSUE THREAD

**Issue by peterfeifanchen** [kohler/click#220] opened 2015-11-13 19:44 UTC
Hi,

  I was trying to build the linuxmodule, but got the following:

for i in click.ko proclikefs.ko; do /usr/bin/install -c -m 644 $i /usr/local/lib/$i; done
/usr/bin/install -c -m 644 Module.symvers /usr/local/lib/click.symvers
../mkinstalldirs /usr/local/include/click-linuxmodule
  INSTALLHEADERS /usr/local/include/click-linuxmodule
/bin/sh: 1: ./fixincludes.pl: not found
make[1]: *** [install-include] Error 127
make[1]: Leaving directory `/home/chenfeif/click/linuxmodule'
make: *** [install-linuxmodule] Error 2

   I actually don't see a fixincludes.pl in the repository, was it removed recently? I configured with --enable-linuxmodules --enable-fixincludes.

Peter

**Comment by kohler** [comment] 2015-11-17 16:01
Whoops! That script got renamed to `click-linuxtool.pl`. The issue is fixed in add2b4b.

**Comment by kohler** [comment] 2015-11-17 16:01
Thanks for the report!

**Closed** 2015-11-17 16:01 UTC
