### ISSUE TITLE
linux_true was not declared

### ISSUE THREAD

**Issue by yxxu** [kohler/click#501] opened 2022-06-18 02:22 UTC
I build click, linux_true was not delcared
ubuntu 22.04

```
config.status: include/click/config-minios.h is unchanged
 make dir=/home/xuyunxiang/ns-3-allinone/bake/source/click-dev/objdir
make[1]: Entering directory '/home/xuyunxiang/ns-3-allinone/bake/source/click-dev/objdir/userlevel'
  FINDELEMENTS elements.conf
  CREATE elements.mk
  AR libclick.a
ar: `u' modifier ignored since `D' is the default (see `U')
  RANLIB libclick.a
  CXX ../../elements/icmp/icmperror.cc
In file included from ../../include/clicknet/ip.h:5,
                 from ../../include/clicknet/icmp.h:4,
                 from ../../elements/icmp/icmperror.cc:20:
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
../../include/click/cxxprotect.h:12:25: error: ‘linux_true’ was not declared in this scope
   12 | # define true           linux_true
      |                         ^~~~~~~~~~
make[1]: *** [elements.mk:414: icmperror.o] Error 1
make[1]: Leaving directory '/home/xuyunxiang/ns-3-allinone/bake/source/click-dev/objdir/userlevel'
make: *** [Makefile:57: userlevel] Error 2

**Comment by tbarbette** [comment] 2022-06-21 12:31
Duplicate of https://github.com/kohler/click/issues/493

**Closed by tbarbette** 2022-06-21 12:31 UTC
