### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by akan1sha** [kohler/click#390] opened 2018-02-05 04:43 UTC
Hello,
    The website for Click OS http://www.read.cs.ucla.edu/click/ is unreachable.Is there a different link I can look at ?

Thanks
Akansha

**Comment by tbarbette** [comment] 2018-02-05 09:05
Duplicate of #377 
Look at https://github.com/kohler/click/wiki ;)

**Closed by tbarbette** 2018-02-05 09:05 UTC
